name: habit_now_clone
description: Just a training trying to reflect an awesome app's front the best I can.

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  repository:
    path: repository
  slang: ^3.15.1
  slang_flutter: ^3.15.0
  styleguide:
    path: styleguide
  table_calendar: 3.0.8
  vrouter: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
