name: styleguide
description: Package with tokens, theme, components

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.4.0
  gap: ^2.0.1
  google_fonts: ^4.0.3
  repository:
    path: ../repository
  table_calendar: 3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
